CREATE TABLE `form_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessType` varchar(255) NOT NULL,
	`businessDuration` varchar(255) NOT NULL,
	`businessLocation` varchar(255) NOT NULL,
	`campaignGoal` varchar(255) NOT NULL,
	`desiredAction` text NOT NULL,
	`dailyBudget` varchar(50) NOT NULL,
	`campaignDuration` varchar(50) NOT NULL,
	`startDate` varchar(50) NOT NULL,
	`targetLocation` varchar(255) NOT NULL,
	`targetAgeGroup` varchar(255) NOT NULL,
	`targetGender` varchar(50) NOT NULL,
	`idealCustomer` text NOT NULL,
	`audienceInterests` text NOT NULL,
	`offering` text NOT NULL,
	`priceRange` varchar(255) NOT NULL,
	`offersDiscounts` text NOT NULL,
	`usp` text NOT NULL,
	`leadDirection` varchar(255) NOT NULL,
	`contactNumber` varchar(20) NOT NULL,
	`leadManager` varchar(255) NOT NULL,
	`responseTime` varchar(255) NOT NULL,
	`previousAds` varchar(10) NOT NULL,
	`pastResults` text,
	`customerDatabase` varchar(10) NOT NULL,
	`facebookPage` varchar(500),
	`instagramPage` varchar(500),
	`website` varchar(500),
	`googleBusinessProfile` varchar(500),
	`availableCreatives` varchar(255) NOT NULL,
	`needNewCreatives` varchar(10) NOT NULL,
	`creativeMessage` text NOT NULL,
	`adAccountType` varchar(255) NOT NULL,
	`hasMetaBusinessManager` varchar(10) NOT NULL,
	`adAccountAccess` varchar(255) NOT NULL,
	`facebookPageAccess` varchar(255) NOT NULL,
	`instagramAccountAccess` varchar(255) NOT NULL,
	`reportingFrequency` varchar(255) NOT NULL,
	`successMetrics` text NOT NULL,
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `form_submissions_id` PRIMARY KEY(`id`)
);
