ALTER TABLE `form_submissions` MODIFY COLUMN `businessType` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `businessDuration` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `businessLocation` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `campaignGoal` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `desiredAction` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `dailyBudget` varchar(50);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `campaignDuration` varchar(50);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `startDate` varchar(50);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `targetLocation` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `targetAgeGroup` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `targetGender` varchar(50);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `idealCustomer` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `audienceInterests` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `offering` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `priceRange` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `offersDiscounts` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `usp` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `leadDirection` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `leadManager` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `responseTime` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `previousAds` varchar(10);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `customerDatabase` varchar(10);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `availableCreatives` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `needNewCreatives` varchar(10);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `creativeMessage` text;--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `adAccountType` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `hasMetaBusinessManager` varchar(10);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `adAccountAccess` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `facebookPageAccess` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `instagramAccountAccess` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `reportingFrequency` varchar(255);--> statement-breakpoint
ALTER TABLE `form_submissions` MODIFY COLUMN `successMetrics` text;